#ifndef LIBUSBY_ERROR_H
#define LIBUSBY_ERROR_H

typedef enum libusby_error
{
	LIBUSBY_SUCCESS = 0,
	LIBUSBY_ERROR_IO = -1,
	LIBUSBY_ERROR_INVALID_PARAM = -2,
	LIBUSBY_ERROR_ACCESS = -3,
	LIBUSBY_ERROR_NO_DEVICE = -4,
	LIBUSBY_ERROR_NOT_FOUND = -5,
	LIBUSBY_ERROR_BUSY = -6,
	LIBUSBY_ERROR_TIMEOUT = -7,
	LIBUSBY_ERROR_OVERFLOW = -8,
	LIBUSBY_ERROR_PIPE = -9,
	LIBUSBY_ERROR_INTERRUPTED = -10,
	LIBUSBY_ERROR_NO_MEM = -11,
	LIBUSBY_ERROR_NOT_SUPPORTED = -12,
	LIBUSBY_ERROR_OTHER = -99,
} libusby_error;

#endif // LIBUSBY_ERROR_H
